spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stock_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

stock:
  api:
    url: https://api.example.com/market/index
    key: ${STOCK_API_KEY}

