server:
  port: 8080

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/your_db_name
    username: your_db_user
    password: your_db_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update # 개발 중엔 update, 운영 시엔 validate 또는 none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  # 에러 메시지를 JSON으로 받을 수 있도록 설정
  mvc:
    problemdetails:
      enabled: true

# JWT
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1시간

# 로깅
logging:
  level:
    root: info
    com.sonny.backend: DEBUG
