name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - airquality-service
          - auth-service
          - dashboard-aggregator-service
          - exchange-service
          - news-service
          - stock-service
          - weather-service
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
      - name: Run tests
        working-directory: backend/${{ matrix.service }}
        run: ./gradlew test

  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      - name: Run tests
        working-directory: frontend
        env:
          CI: 'true'
        run: npm test
