name: Sentiment CI/CD → ECR (Python)

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/news-service/sentiment/**"
      - ".github/workflows/sentiment-ci.yml"
  pull_request:
    paths:
      - "backend/news-service/sentiment/**"

env:
  AWS_REGION: ap-northeast-2
  PROJECT: dailybriefing
  SERVICE: sentiment-service           # ← ECR 리포 이름과 일치

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/news-service/sentiment

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint (optional)
        run: |
          pip install flake8 || true
          flake8 . || true

      - name: Tests (optional)
        run: |
          pip install pytest || true
          pytest -q || true

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/news-service/sentiment
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.PROJECT }}/${{ env.SERVICE }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.PROJECT }}/${{ env.SERVICE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Done
        run: echo "✅ Pushed ${{ env.SERVICE }} to ECR"
