name: Sentiment CI (Python)

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/news-service/sentiment/**"
      - ".github/workflows/sentiment-ci.yml"
  pull_request:
    paths:
      - "backend/news-service/sentiment/**"

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/news-service/sentiment
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 선택: 코드 품질 검사(있으면 좋음)
      - name: Lint (flake8)
        run: |
          pip install flake8 || true
          flake8 . || true

      # 선택: 테스트(있으면 좋음)
      - name: Test (pytest)
        run: |
          pip install pytest || true
          pytest -q || true

      # 최소 스모크 테스트: 실행만 되는지 확인(서비스 진입점 바꿔도 됨)
      - name: Smoke run
        run: |
          python sentiment_service.py --help || true

      - name: Done
        run: echo "✅ Sentiment workflow connected successfully"

